<?php

namespace App\Enum;

enum PermissionCode: string
{
    case CATALOG_PRODUCT_CREATE = 'CATALOG_PRODUCT_CREATE';
    case CATALOG_PRODUCT_READ_LIST = 'CATALOG_PRODUCT_READ_LIST';
    case CATALOG_PRODUCT_READ_STATUS_TYPES = 'CATALOG_PRODUCT_READ_STATUS_TYPES';
    case CATALOG_PRODUCT_UPDATE = 'CATALOG_PRODUCT_UPDATE';
    case CATALOG_PRODUCT_UPDATE_PRICE_RUB = 'CATALOG_PRODUCT_UPDATE_PRICE_RUB';

    case CATALOG_CATEGORY_CREATE = 'CATALOG_CATEGORY_CREATE';
    case CATALOG_CATEGORY_UPDATE = 'CATALOG_CATEGORY_UPDATE';
    case CATALOG_CATEGORY_READ_LIST = 'CATALOG_CATEGORY_READ_LIST';
    case CATALOG_CATEGORY_READ_TREE = 'CATALOG_CATEGORY_READ_TREE';
    case CATALOG_CATEGORY_READ_CONCRETE = 'CATALOG_CATEGORY_READ_CONCRETE';

    case CUSTOMER_ORDER_CANCEL = 'CUSTOMER_ORDER_CANCEL';
    case CUSTOMER_ORDER_COMPLETE = 'CUSTOMER_ORDER_COMPLETE';

    case INVENTORY_PRODUCT_STOCK_MANAGEMENT_UPDATE_WAREHOUSE_STOCK = 'INVENTORY_PRODUCT_STOCK_MANAGEMENT_UPDATE_WAREHOUSE_STOCK';
    case INVENTORY_PRODUCT_STOCK_MANAGEMENT_READ_PRODUCT_WH_STOCKS_LIST = 'INVENTORY_PRODUCT_STOCK_MANAGEMENT_READ_PRODUCT_WH_STOCKS_LIST';
    case INVENTORY_PRODUCT_STOCK_MANAGEMENT_READ_WH_TRANSACTIONS_LIST = 'INVENTORY_PRODUCT_STOCK_MANAGEMENT_READ_WH_TRANSACTIONS_LIST';

    case INVENTORY_WAREHOUSE_CREATE = 'INVENTORY_WAREHOUSE_CREATE';
    case INVENTORY_WAREHOUSE_UPDATE = 'INVENTORY_WAREHOUSE_UPDATE';
    case INVENTORY_WAREHOUSE_READ_LIST = 'INVENTORY_WAREHOUSE_READ_LIST';
}
