<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260914092021 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'initial migrations';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE addresses (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address VARCHAR(255) DEFAULT NULL, mail_index VARCHAR(20) DEFAULT NULL, country VARCHAR(100) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE c_wallt_transaction_purpose_types (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(30) NOT NULL, label VARCHAR(120) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8C8ADE4677153098 ON c_wallt_transaction_purpose_types (code)');
        $this->addSql('CREATE TABLE cart_items (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id BIGINT NOT NULL, cart_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_cart_product ON cart_items (cart_id, product_id)');
        $this->addSql('CREATE INDEX IDX_BEF484454584665A ON cart_items (product_id)');
        $this->addSql('CREATE INDEX IDX_BEF484451AD5CDBF ON cart_items (cart_id)');
        $this->addSql('CREATE TABLE categories (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, parent_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AF34668727ACA70 ON categories (parent_id)');
        $this->addSql('CREATE TABLE customer_carts (customer_id INT NOT NULL, PRIMARY KEY (customer_id))');
        $this->addSql('CREATE TABLE customer_order_status_types (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(120) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C9B8318E77153098 ON customer_order_status_types (code)');
        $this->addSql('CREATE TABLE customer_orders (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_id INT NOT NULL, status_type_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_54EA21BF9395C3F3 ON customer_orders (customer_id)');
        $this->addSql('CREATE INDEX IDX_54EA21BFCD9CFB16 ON customer_orders (status_type_id)');
        $this->addSql('CREATE TABLE customer_wallet_transactions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, old_balance NUMERIC(10, 2) NOT NULL, new_balance NUMERIC(10, 2) NOT NULL, delta NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, wallet_id INT NOT NULL, purpose_type_id SMALLINT NOT NULL, user_id INT NOT NULL, order_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9962F34E712520F3 ON customer_wallet_transactions (wallet_id)');
        $this->addSql('CREATE INDEX IDX_9962F34E5D216651 ON customer_wallet_transactions (purpose_type_id)');
        $this->addSql('CREATE INDEX IDX_9962F34EA76ED395 ON customer_wallet_transactions (user_id)');
        $this->addSql('CREATE INDEX IDX_9962F34E8D9F6D38 ON customer_wallet_transactions (order_id)');
        $this->addSql('CREATE TABLE customer_wallets (balance NUMERIC(10, 2) NOT NULL, customer_id INT NOT NULL, PRIMARY KEY (customer_id))');
        $this->addSql('CREATE TABLE customers (id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE order_custm_wallt_transactions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id BIGINT NOT NULL, custm_wallet_tran_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_555CCB418D9F6D38 ON order_custm_wallt_transactions (order_id)');
        $this->addSql('CREATE INDEX IDX_555CCB4192C45B83 ON order_custm_wallt_transactions (custm_wallet_tran_id)');
        $this->addSql('CREATE TABLE order_item_reservation_status_types (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(120) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3E97DEA977153098 ON order_item_reservation_status_types (code)');
        $this->addSql('CREATE TABLE order_item_warehouse_reservations (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reserved_quantity INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_item_id BIGINT NOT NULL, warehouse_id BIGINT NOT NULL, status_type_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E91AB4F6E415FB15 ON order_item_warehouse_reservations (order_item_id)');
        $this->addSql('CREATE INDEX IDX_E91AB4F65080ECDE ON order_item_warehouse_reservations (warehouse_id)');
        $this->addSql('CREATE INDEX IDX_E91AB4F6CD9CFB16 ON order_item_warehouse_reservations (status_type_id)');
        $this->addSql('CREATE TABLE order_items (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit_price_rub NUMERIC(10, 2) NOT NULL, price_total_rub NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id BIGINT NOT NULL, order_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_62809DB04584665A ON order_items (product_id)');
        $this->addSql('CREATE INDEX IDX_62809DB08D9F6D38 ON order_items (order_id)');
        $this->addSql('CREATE TABLE permissions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, label VARCHAR(120) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DEDCC6F77153098 ON permissions (code)');
        $this->addSql('CREATE TABLE role_permissions (permission_id BIGINT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (permission_id, role_id))');
        $this->addSql('CREATE INDEX IDX_1FBA94E6FED90CCA ON role_permissions (permission_id)');
        $this->addSql('CREATE INDEX IDX_1FBA94E6D60322AC ON role_permissions (role_id)');
        $this->addSql('CREATE TABLE product_status_types (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, label VARCHAR(120) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23CEFAAB77153098 ON product_status_types (code)');
        $this->addSql('CREATE TABLE product_wh_stocks (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, physical_quantity INT NOT NULL, reserved_quantity INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id BIGINT NOT NULL, warehouse_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_product_wh ON product_wh_stocks (product_id, warehouse_id)');
        $this->addSql('CREATE INDEX IDX_2DCD17C94584665A ON product_wh_stocks (product_id)');
        $this->addSql('CREATE INDEX IDX_2DCD17C95080ECDE ON product_wh_stocks (warehouse_id)');
        $this->addSql('CREATE TABLE products (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) NOT NULL, description TEXT NOT NULL, price_rub NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status_type_id SMALLINT NOT NULL, category_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B3BA5A5A77153098 ON products (code)');
        $this->addSql('CREATE INDEX IDX_B3BA5A5ACD9CFB16 ON products (status_type_id)');
        $this->addSql('CREATE INDEX IDX_B3BA5A5A12469DE2 ON products (category_id)');
        $this->addSql('CREATE TABLE roles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, label VARCHAR(120) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B63E2EC777153098 ON roles (code)');
        $this->addSql('CREATE TABLE user_status_types (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, label VARCHAR(120) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2EA6A4C277153098 ON user_status_types (code)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status_type_id SMALLINT NOT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE INDEX IDX_1483A5E9CD9CFB16 ON users (status_type_id)');
        $this->addSql('CREATE TABLE user_permissions (user_id INT NOT NULL, permission_id BIGINT NOT NULL, PRIMARY KEY (user_id, permission_id))');
        $this->addSql('CREATE INDEX IDX_84F605FAA76ED395 ON user_permissions (user_id)');
        $this->addSql('CREATE INDEX IDX_84F605FAFED90CCA ON user_permissions (permission_id)');
        $this->addSql('CREATE TABLE user_roles (user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_54FCD59FA76ED395 ON user_roles (user_id)');
        $this->addSql('CREATE INDEX IDX_54FCD59FD60322AC ON user_roles (role_id)');
        $this->addSql('CREATE TABLE warehouse_stock_transactions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, old_quantity INT NOT NULL, new_quantity INT NOT NULL, delta INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id BIGINT NOT NULL, warehouse_id BIGINT NOT NULL, purpose_type_id SMALLINT NOT NULL, product_warehouse_stock_id BIGINT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_28D5132F4584665A ON warehouse_stock_transactions (product_id)');
        $this->addSql('CREATE INDEX IDX_28D5132F5080ECDE ON warehouse_stock_transactions (warehouse_id)');
        $this->addSql('CREATE INDEX IDX_28D5132F5D216651 ON warehouse_stock_transactions (purpose_type_id)');
        $this->addSql('CREATE INDEX IDX_28D5132FDF5386CA ON warehouse_stock_transactions (product_warehouse_stock_id)');
        $this->addSql('CREATE INDEX IDX_28D5132FA76ED395 ON warehouse_stock_transactions (user_id)');
        $this->addSql('CREATE TABLE warehouses (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, address_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AFE9C2B7F5B7AF75 ON warehouses (address_id)');
        $this->addSql('CREATE TABLE wh_st_transaction_purpose_types (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, label VARCHAR(120) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ADB3C4CD77153098 ON wh_st_transaction_purpose_types (code)');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT FK_BEF484454584665A FOREIGN KEY (product_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT FK_BEF484451AD5CDBF FOREIGN KEY (cart_id) REFERENCES customer_carts (customer_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF34668727ACA70 FOREIGN KEY (parent_id) REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_carts ADD CONSTRAINT FK_80353F979395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_orders ADD CONSTRAINT FK_54EA21BF9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_orders ADD CONSTRAINT FK_54EA21BFCD9CFB16 FOREIGN KEY (status_type_id) REFERENCES customer_order_status_types (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_wallet_transactions ADD CONSTRAINT FK_9962F34E712520F3 FOREIGN KEY (wallet_id) REFERENCES customer_wallets (customer_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_wallet_transactions ADD CONSTRAINT FK_9962F34E5D216651 FOREIGN KEY (purpose_type_id) REFERENCES c_wallt_transaction_purpose_types (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_wallet_transactions ADD CONSTRAINT FK_9962F34EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_wallet_transactions ADD CONSTRAINT FK_9962F34E8D9F6D38 FOREIGN KEY (order_id) REFERENCES customer_orders (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_wallets ADD CONSTRAINT FK_8AA70ED29395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customers ADD CONSTRAINT FK_62534E21BF396750 FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_custm_wallt_transactions ADD CONSTRAINT FK_555CCB418D9F6D38 FOREIGN KEY (order_id) REFERENCES customer_orders (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_custm_wallt_transactions ADD CONSTRAINT FK_555CCB4192C45B83 FOREIGN KEY (custm_wallet_tran_id) REFERENCES customer_wallet_transactions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item_warehouse_reservations ADD CONSTRAINT FK_E91AB4F6E415FB15 FOREIGN KEY (order_item_id) REFERENCES order_items (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item_warehouse_reservations ADD CONSTRAINT FK_E91AB4F65080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item_warehouse_reservations ADD CONSTRAINT FK_E91AB4F6CD9CFB16 FOREIGN KEY (status_type_id) REFERENCES order_item_reservation_status_types (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT FK_62809DB04584665A FOREIGN KEY (product_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT FK_62809DB08D9F6D38 FOREIGN KEY (order_id) REFERENCES customer_orders (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6FED90CCA FOREIGN KEY (permission_id) REFERENCES permissions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6D60322AC FOREIGN KEY (role_id) REFERENCES roles (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_wh_stocks ADD CONSTRAINT FK_2DCD17C94584665A FOREIGN KEY (product_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_wh_stocks ADD CONSTRAINT FK_2DCD17C95080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5ACD9CFB16 FOREIGN KEY (status_type_id) REFERENCES product_status_types (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9CD9CFB16 FOREIGN KEY (status_type_id) REFERENCES user_status_types (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_permissions ADD CONSTRAINT FK_84F605FAA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_permissions ADD CONSTRAINT FK_84F605FAFED90CCA FOREIGN KEY (permission_id) REFERENCES permissions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FD60322AC FOREIGN KEY (role_id) REFERENCES roles (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE warehouse_stock_transactions ADD CONSTRAINT FK_28D5132F4584665A FOREIGN KEY (product_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE warehouse_stock_transactions ADD CONSTRAINT FK_28D5132F5080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE warehouse_stock_transactions ADD CONSTRAINT FK_28D5132F5D216651 FOREIGN KEY (purpose_type_id) REFERENCES wh_st_transaction_purpose_types (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE warehouse_stock_transactions ADD CONSTRAINT FK_28D5132FDF5386CA FOREIGN KEY (product_warehouse_stock_id) REFERENCES product_wh_stocks (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE warehouse_stock_transactions ADD CONSTRAINT FK_28D5132FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE warehouses ADD CONSTRAINT FK_AFE9C2B7F5B7AF75 FOREIGN KEY (address_id) REFERENCES addresses (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT FK_BEF484454584665A');
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT FK_BEF484451AD5CDBF');
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT FK_3AF34668727ACA70');
        $this->addSql('ALTER TABLE customer_carts DROP CONSTRAINT FK_80353F979395C3F3');
        $this->addSql('ALTER TABLE customer_orders DROP CONSTRAINT FK_54EA21BF9395C3F3');
        $this->addSql('ALTER TABLE customer_orders DROP CONSTRAINT FK_54EA21BFCD9CFB16');
        $this->addSql('ALTER TABLE customer_wallet_transactions DROP CONSTRAINT FK_9962F34E712520F3');
        $this->addSql('ALTER TABLE customer_wallet_transactions DROP CONSTRAINT FK_9962F34E5D216651');
        $this->addSql('ALTER TABLE customer_wallet_transactions DROP CONSTRAINT FK_9962F34EA76ED395');
        $this->addSql('ALTER TABLE customer_wallet_transactions DROP CONSTRAINT FK_9962F34E8D9F6D38');
        $this->addSql('ALTER TABLE customer_wallets DROP CONSTRAINT FK_8AA70ED29395C3F3');
        $this->addSql('ALTER TABLE customers DROP CONSTRAINT FK_62534E21BF396750');
        $this->addSql('ALTER TABLE order_custm_wallt_transactions DROP CONSTRAINT FK_555CCB418D9F6D38');
        $this->addSql('ALTER TABLE order_custm_wallt_transactions DROP CONSTRAINT FK_555CCB4192C45B83');
        $this->addSql('ALTER TABLE order_item_warehouse_reservations DROP CONSTRAINT FK_E91AB4F6E415FB15');
        $this->addSql('ALTER TABLE order_item_warehouse_reservations DROP CONSTRAINT FK_E91AB4F65080ECDE');
        $this->addSql('ALTER TABLE order_item_warehouse_reservations DROP CONSTRAINT FK_E91AB4F6CD9CFB16');
        $this->addSql('ALTER TABLE order_items DROP CONSTRAINT FK_62809DB04584665A');
        $this->addSql('ALTER TABLE order_items DROP CONSTRAINT FK_62809DB08D9F6D38');
        $this->addSql('ALTER TABLE role_permissions DROP CONSTRAINT FK_1FBA94E6FED90CCA');
        $this->addSql('ALTER TABLE role_permissions DROP CONSTRAINT FK_1FBA94E6D60322AC');
        $this->addSql('ALTER TABLE product_wh_stocks DROP CONSTRAINT FK_2DCD17C94584665A');
        $this->addSql('ALTER TABLE product_wh_stocks DROP CONSTRAINT FK_2DCD17C95080ECDE');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5ACD9CFB16');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5A12469DE2');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9CD9CFB16');
        $this->addSql('ALTER TABLE user_permissions DROP CONSTRAINT FK_84F605FAA76ED395');
        $this->addSql('ALTER TABLE user_permissions DROP CONSTRAINT FK_84F605FAFED90CCA');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FA76ED395');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FD60322AC');
        $this->addSql('ALTER TABLE warehouse_stock_transactions DROP CONSTRAINT FK_28D5132F4584665A');
        $this->addSql('ALTER TABLE warehouse_stock_transactions DROP CONSTRAINT FK_28D5132F5080ECDE');
        $this->addSql('ALTER TABLE warehouse_stock_transactions DROP CONSTRAINT FK_28D5132F5D216651');
        $this->addSql('ALTER TABLE warehouse_stock_transactions DROP CONSTRAINT FK_28D5132FDF5386CA');
        $this->addSql('ALTER TABLE warehouse_stock_transactions DROP CONSTRAINT FK_28D5132FA76ED395');
        $this->addSql('ALTER TABLE warehouses DROP CONSTRAINT FK_AFE9C2B7F5B7AF75');
        $this->addSql('DROP TABLE addresses');
        $this->addSql('DROP TABLE c_wallt_transaction_purpose_types');
        $this->addSql('DROP TABLE cart_items');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE customer_carts');
        $this->addSql('DROP TABLE customer_order_status_types');
        $this->addSql('DROP TABLE customer_orders');
        $this->addSql('DROP TABLE customer_wallet_transactions');
        $this->addSql('DROP TABLE customer_wallets');
        $this->addSql('DROP TABLE customers');
        $this->addSql('DROP TABLE order_custm_wallt_transactions');
        $this->addSql('DROP TABLE order_item_reservation_status_types');
        $this->addSql('DROP TABLE order_item_warehouse_reservations');
        $this->addSql('DROP TABLE order_items');
        $this->addSql('DROP TABLE permissions');
        $this->addSql('DROP TABLE role_permissions');
        $this->addSql('DROP TABLE product_status_types');
        $this->addSql('DROP TABLE product_wh_stocks');
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE user_status_types');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE user_permissions');
        $this->addSql('DROP TABLE user_roles');
        $this->addSql('DROP TABLE warehouse_stock_transactions');
        $this->addSql('DROP TABLE warehouses');
        $this->addSql('DROP TABLE wh_st_transaction_purpose_types');
    }
}
